"""
LangGraph state definition for the impact analysis workflow.
"""
from typing import TypedDict


class ImpactAnalysisState(TypedDict):
    """
    Shared state passed through the LangGraph workflow.
    Each node reads from and writes to this state.
    """
    project_id: str
    pr_number: int
    changed_files: list[str]

    # Fed in by analysis_service before the graph runs (requires a GitHub
    # API call, so it's resolved once up front rather than inside a node)
    diff_size: int

    # Computed by graph traversal
    directly_affected: list[str]
    transitively_affected: list[str]

    # Computed by risk scoring
    risk_score: float
    risk_level: str  # 'low' | 'medium' | 'high'

    # Retrieved from vector DB
    similar_bugs: list[dict]

    # Generated by LLM
    explanation: str
    heuristic_test_files: list[str]
    llm_testing_areas: list[str]

    # Final output
    raw_llm_output: str

    # Generated by LLM
    explanation: str
    heuristic_test_files: list[str]
    llm_testing_areas: list[str]
    suggested_tests: list[str]  # union of the two above, capped -- the single
                                 # source of truth downstream (comment + DB)
                                 # instead of every consumer re-deriving it

    # Built by format_output, consumed by post_github_comment
    comment_markdown: str

    # Populated by post_github_comment (None if posting failed/was skipped)
    github_comment_id: int | None

    # Final output
    raw_llm_output: str