"""
LangGraph state definition for the impact analysis workflow.
"""
from typing import TypedDict


class ImpactAnalysisState(TypedDict):
    """
    Shared state passed through the LangGraph workflow.
    Each node reads from and writes to this state.
    """
    project_id: str
    pr_number: int
    changed_files: list[str]

    # Computed by graph traversal
    directly_affected: list[str]
    transitively_affected: list[str]

    # Computed by risk scoring
    risk_score: float
    risk_level: str  # 'low' | 'medium' | 'high'

    # Retrieved from vector DB
    similar_bugs: list[dict]

    # Generated by LLM
    explanation: str
    suggested_tests: list[str]

    # Final output
    raw_llm_output: str
